### ISSUE TITLE
Difference with Covid19EstimationHydroxychloroquine package

### ISSUE THREAD

**Issue by obonyojimmy** [ohdsi-studies/Covid19EstimationHydroxychloroquine2#1]
Hi first and foremost , congrats for writing this awesome package , am however confused if this has any difference with https://github.com/ohdsi-studies/Covid19EstimationHydroxychloroquine , thanks.

**Comment by jamieweaver** [comment]
thanks! it differs only in the outcomes evaluated. all exposure cohort definitions and statistical methods are identical to the other hcq study.
